### ISSUE TITLE
Como adicionar um busca?

### ISSUE THREAD

**Issue by henriquelucas** [JhonathanRibeiro/Cadastro-simples-PHP#1]
Perfeito o script, simplesmente era algo que estava procurando para um proposito aqui meu. Fiz algumas modificações nele. Você sabe me informar como poderia adicionar uma barra de pesquisa para exibir apenas o resultado de um nome especifico.

Por exemplo:
Adicione o Campo de busca no **consultas.php** 
 ` <form action="busca.php" method="GET">
		   <input type="text" name="pesquisa" size="50" placeholder="Número da NFe">
	    </form>`

em **busca.php** adicionei:

`<?php include_once 'includes/header.inc.php' ?>
<?php include_once 'includes/menu.inc.php' ?>

<div class="row container">
    <div class="col s12">
        <h5 class="light">Consultas</h5><hr>

        <table class="striped">
            <thead>
                <tr>
                    <th>Número da NFe</th>
                    <th>Fornecedor</th>
					<th>Conferente</th>
					<th>Data</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    include_once 'conexao.php';
                    $busca = $_POST['busca'];

                    $querySelect = $link->query("select * from tb_clientes WHERE like '%".$busca."%' ");
                    while($registros = $querySelect->fetch_assoc()):
                        $id       = $registros['id'];
                        $nome     = $registros['nome'];
	                    $fornecedor = $registros['fornecedor'];
                        $conferente    = $registros['conferente'];
	                    $date   = $registros['date'];

                        echo "
                          <tr>
                          <td>$nome</td>
                          <td>$fornecedor</td>
                          <td>$conferente</td>
                          <td>$date</td>
                          </tr>
						";
                    endwhile;

                ?>
            </tbody>
        </table>
    </div>
</div>

Porém o resultado não é exibido, você poderia me dar uma força nessa implementação?

Desde já agradeço pelo projeto.

**Comment by JhonathanRibeiro** [comment]
Olá @henriquelucas, que bom, fico feliz em poder ajudar. =) 

Analisei o seu código, a pesquisa não funciona pois falta o campo de referência após o WHERE e também a concatenação das porcentagens, você pode remover sem problemas, ficaria assim('%$busca%') sem os parênteses hehe..., O metodo do form também, voce informou o GET, e no busca.php você tenta recuperar via POST, só alterar para GET que ta tudo certo.

Você pode informar um ou múltiplos campos para realizar a pesquisa também, fica a seu critério, é bem simples de se fazer, para isso você pode utilizar a cláusula OR do SQL, vou deixar um exemplo para você testar, lembrando que atualizei o código, recomendo clonar o projeto e analisar as alterações que fiz. ;)

**Busca com um campo:**
`$querySelect = $link->query("SELECT * FROM clientes WHERE nome LIKE '%$busca%' ");`

**Busca com vários campos:**
` $querySelect = $link->query("SELECT * FROM clientes WHERE nome LIKE '%$busca%' OR fornecedor LIKE  '%$busca%'");`

> **Obs:** Eu precisei alterar o nome do banco de **db_cadastros** para **db_clientes** pois estava utilizando em outro projeto, alterei o nome da tabela tbm, apenas removi o prefixo **tb_** do inicio, ficou como **clientes**.

Espero ter ajudado, grande abraço! =)

**Minhas redes sociais**
[![Instagram Badge](https://img.shields.io/badge/-Instagram-B353A5?style=flat-square&labelColor=B353A5&logo=instagram&logoColor=white&link=https://www.instagram.com/jhonathan.rb)](https://www.instagram.com/jhonathan.rb)
[![Facebook](https://img.shields.io/badge/Facebook-1877F2?style=for-the-badge&logo=facebook&logoColor=white)](https://www.facebook.com/rjhonathan.ribeiro/)
[![Twitter](https://img.shields.io/twitter/url/https/twitter.com/cloudposse.svg?style=social&label=Follow%20jhonathanribeiro)](https://twitter.com/jhonathanjbr)

**Comment by JhonathanRibeiro** [comment]
Olá @henriquelucas, que bom, fico feliz em poder ajudar. =) 

Analisei o seu código, a pesquisa não funciona pois falta o campo de referência após o WHERE e também a concatenação das porcentagens, você pode remover sem problemas, ficaria assim('%$busca%') sem os parênteses hehe..., O metodo do form também, voce informou o GET, e no busca.php você tenta recuperar via POST, só alterar para GET que ta tudo certo.

Você pode informar um ou múltiplos campos para realizar a pesquisa também, fica a seu critério, é bem simples de se fazer, para isso você pode utilizar a cláusula OR do SQL, vou deixar um exemplo para você testar, lembrando que atualizei o código, recomendo clonar o projeto e analisar as alterações que fiz. ;)

**Busca com um campo:**
`$querySelect = $link->query("SELECT * FROM clientes WHERE nome LIKE '%$busca%' ");`

**Busca com vários campos:**
` $querySelect = $link->query("SELECT * FROM clientes WHERE nome LIKE '%$busca%' OR fornecedor LIKE  '%$busca%'");`

> **Obs:** Eu precisei alterar o nome do banco de **db_cadastros** para **db_clientes** pois estava utilizando em outro projeto, alterei o nome da tabela tbm, apenas removi o prefixo **tb_** do inicio, ficou como **clientes**.

Espero ter ajudado, grande abraço! =)

**Minhas redes sociais**
[![Instagram Badge](https://img.shields.io/badge/-Instagram-B353A5?style=flat-square&labelColor=B353A5&logo=instagram&logoColor=white&link=https://www.instagram.com/jhonathan.rb)](https://www.instagram.com/jhonathan.rb)
[![Facebook](https://img.shields.io/badge/Facebook-1877F2?style=for-the-badge&logo=facebook&logoColor=white)](https://www.facebook.com/rjhonathan.ribeiro/)
[![Twitter](https://img.shields.io/twitter/url/https/twitter.com/cloudposse.svg?style=social&label=Follow%20jhonathanribeiro)](https://twitter.com/jhonathanjbr)

**Comment by JhonathanRibeiro** [comment]
> Perfeito o script, simplesmente era algo que estava procurando para um proposito aqui meu. Fiz algumas modificações nele. Você sabe me informar como poderia adicionar uma barra de pesquisa para exibir apenas o resultado de um nome especifico.
> 
> Por exemplo:
> Adicione o Campo de busca no **consultas.php**
> ` <form action="busca.php" method="GET"> <input type="text" name="pesquisa" size="50" placeholder="Número da NFe"> </form>`
> 
> em **busca.php** adicionei:
> 
> `
> 
> ##### Consultas
> ```
>     <table class="striped">
>         <thead>
>             <tr>
>                 <th>Número da NFe</th>
>                 <th>Fornecedor</th>
> 				<th>Conferente</th>
> 				<th>Data</th>
>             </tr>
>         </thead>
>         <tbody>
>             <?php
>                 include_once 'conexao.php';
>                 $busca = $_POST['busca'];
> 
>                 $querySelect = $link->query("select * from tb_clientes WHERE like '%".$busca."%' ");
>                 while($registros = $querySelect->fetch_assoc()):
>                     $id       = $registros['id'];
>                     $nome     = $registros['nome'];
>                     $fornecedor = $registros['fornecedor'];
>                     $conferente    = $registros['conferente'];
>                     $date   = $registros['date'];
> 
>                     echo "
>                       <tr>
>                       <td>$nome</td>
>                       <td>$fornecedor</td>
>                       <td>$conferente</td>
>                       <td>$date</td>
>                       </tr>
> 					";
>                 endwhile;
> 
>             ?>
>         </tbody>
>     </table>
> </div>
> ```
> 
> Porém o resultado não é exibido, você poderia me dar uma força nessa implementação?
> 
> Desde já agradeço pelo projeto.

Olá @henriquelucas, que bom, fico feliz em poder ajudar. =) 

Analisei o seu código, a pesquisa não funciona pois falta o campo de referência após o WHERE e também a concatenação das porcentagens, você pode remover sem problemas, ficaria assim('%$busca%') sem os parênteses hehe..., O metodo do form também, voce informou o GET, e no busca.php você tenta recuperar via POST, só alterar para GET que ta tudo certo.

Você pode informar um ou múltiplos campos para realizar a pesquisa também, fica a seu critério, é bem simples de se fazer, para isso você pode utilizar a cláusula OR do SQL, vou deixar um exemplo para você testar, lembrando que atualizei o código, recomendo clonar o projeto e analisar as alterações que fiz. ;)

**Busca com um campo:**
`$querySelect = $link->query("SELECT * FROM clientes WHERE nome LIKE '%$busca%' ");`

**Busca com vários campos:**
` $querySelect = $link->query("SELECT * FROM clientes WHERE nome LIKE '%$busca%' OR fornecedor LIKE  '%$busca%'");`

> **Obs:** Eu precisei alterar o nome do banco de **db_cadastros** para **db_clientes** pois estava utilizando em outro projeto, alterei o nome da tabela tbm, apenas removi o prefixo **tb_** do inicio, ficou como **clientes**.

Espero ter ajudado, grande abraço! =)

**Minhas redes sociais**
[![Instagram Badge](https://img.shields.io/badge/-Instagram-B353A5?style=flat-square&labelColor=B353A5&logo=instagram&logoColor=white&link=https://www.instagram.com/jhonathan.rb)](https://www.instagram.com/jhonathan.rb)
[![Facebook](https://img.shields.io/badge/Facebook-1877F2?style=for-the-badge&logo=facebook&logoColor=white)](https://www.facebook.com/rjhonathan.ribeiro/)
[![Twitter](https://img.shields.io/twitter/url/https/twitter.com/cloudposse.svg?style=social&label=Follow%20jhonathanribeiro)](https://twitter.com/jhonathanjbr)

**Comment by henriquelucas** [comment]
Opa Jhonathan, sou novo com programação rsrs. Me Desculpa a demora no Feedback. Eu tinha conseguido resolver o problema. Agora estou tentando implementar um tela de Login para segurança dos dados.
